# Generated by Django 4.1.7 on 2023-06-02 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thread",
            old_name="user_2",
            new_name="landlord",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="user_1",
            new_name="tenant",
        ),
    ]
