# Generated by Django 4.1.7 on 2023-06-02 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_rename_user_2_thread_landlord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
