# Generated by Django 4.1.7 on 2023-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(),
        ),
    ]
