# Generated by Django 4.1.7 on 2023-06-02 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_appointment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-created_at"]},
        ),
    ]
