# Generated by Django 4.1.7 on 2023-06-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "pending"),
                    (1, "approved"),
                    (2, "rejected"),
                    (3, "canceled"),
                    (4, "passed"),
                ],
                default=0,
            ),
        ),
    ]
