# Generated by Django 4.1.7 on 2023-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_options_property_facilities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="category",
        ),
        migrations.AddField(
            model_name="property",
            name="categories",
            field=models.ManyToManyField(to="properties.category"),
        ),
    ]
