# Generated by Django 4.1.7 on 2023-04-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-id"]},
        ),
    ]
