# Generated by Django 4.1.7 on 2023-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_facility_remove_property_facilities_propertyfacility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfacility",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
