# Generated by Django 4.1.7 on 2023-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_propertyfacility_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfacility",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
