# Generated by Django 4.1.7 on 2023-05-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_propertyfacility_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfacility",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.facility",
            ),
        ),
    ]
