# Generated by Django 4.1.7 on 2023-05-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_property_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
