# Generated by Django 4.1.7 on 2023-05-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_property_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.category",
            ),
        ),
    ]
