# Generated by Django 4.1.7 on 2023-05-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0010_remove_property_categories_remove_property_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyfacility",
            old_name="amount",
            new_name="count",
        ),
    ]
