# Generated by Django 4.1.7 on 2023-05-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_rename_amount_propertyfacility_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="address",
            new_name="location",
        ),
    ]
