# Generated by Django 4.1.7 on 2023-05-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_remove_property_location_propertylocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotspotNode",
            fields=[
                ("node_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField()),
                (
                    "panorama",
                    models.ImageField(max_length=255, upload_to="panorama_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VirtualTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defaultViewPosition_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "defaultViewPosition_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("initialView", models.UUIDField(null=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_tour",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                ("marker_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField()),
                ("tooltip", models.CharField(blank=True, max_length=255)),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("anchor", models.CharField(blank=True, max_length=255)),
                ("linksTo", models.UUIDField(null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="properties.hotspotnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodeId", models.UUIDField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="properties.hotspotnode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotspotnode",
            name="virtual_tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotspotNodes",
                to="properties.virtualtour",
            ),
        ),
    ]
