# Generated by Django 4.1.7 on 2023-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_hotspotnode_virtualtour_marker_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="availability",
        ),
        migrations.AddField(
            model_name="property",
            name="visiting_hours",
            field=models.JSONField(default=dict),
        ),
    ]
