# Generated by Django 4.1.7 on 2023-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_property_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotspotnode",
            name="panorama",
            field=models.ImageField(upload_to="panorama_images/"),
        ),
    ]
