# Generated by Django 4.1.7 on 2023-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_alter_favorites_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
