# Generated by Django 4.1.7 on 2023-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0022_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="amount",
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
