# Generated by Django 4.1.7 on 2023-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0023_alter_property_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfacility",
            name="count",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
