# Generated by Django 4.1.7 on 2023-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Withdrawn"),
                    (3, "Rejected"),
                ],
                default=0,
            ),
        ),
    ]
