# Generated by Django 4.1.7 on 2023-04-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-id"]},
        ),
    ]
