# Generated by Django 4.1.7 on 2023-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0005_remove_contract_property_remove_contract_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"get_latest_by": ["start_date"]},
        ),
    ]
