# Generated by Django 4.1.7 on 2023-05-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="by",
            new_name="user",
        ),
    ]
