# Generated by Django 4.1.7 on 2023-05-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_by_review_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-date",)},
        ),
    ]
