# Generated by Django 4.1.7 on 2023-06-03 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-date", "-rating")},
        ),
    ]
