# Generated by Django 4.1.7 on 2023-05-27 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tx_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("4f25d8d1-b1aa-4001-b426-afe633b22c9b"),
            ),
        ),
    ]
