# Generated by Django 4.1.7 on 2023-05-27 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_tx_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tx_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("d403ee11-1856-475f-b72f-c58c7da36171"),
            ),
        ),
    ]
