# Generated by Django 4.1.7 on 2023-05-27 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_tx_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="checkout_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_ref",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("9977b400-49cb-4dd6-89c9-03025f4365fa"),
            ),
        ),
    ]
