# Generated by Django 4.1.7 on 2023-05-27 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transaction_checkout_url_alter_transaction_tx_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tx_ref",
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
