# Generated by Django 4.1.7 on 2023-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_tx_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "paid"),
                    (3, "failed"),
                    (4, "withdrawal request approved"),
                    (5, "withdrawal request denied"),
                ],
                default=1,
            ),
        ),
    ]
