# Generated by Django 4.1.7 on 2023-05-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_alter_transaction_payment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-payment_date"]},
        ),
    ]
