# Generated by Django 4.1.7 on 2023-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_alter_transaction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_detail",
            field=models.JSONField(default=dict),
        ),
    ]
