# Generated by Django 4.1.7 on 2023-06-02 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0012_transaction_bank_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
