# Generated by Django 4.1.7 on 2023-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0015_alter_userrentedproperties_property"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrentedproperties",
            options={"get_latest_by": ["id"]},
        ),
    ]
