# Generated by Django 4.1.7 on 2023-06-16 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0016_alter_userrentedproperties_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrentedproperties",
            options={"get_latest_by": ["start_date"]},
        ),
    ]
