# Generated by Django 4.1.7 on 2023-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Tenant"),
                    (2, "Landlord"),
                    (3, "Financial Manager"),
                    (4, "Listing Manager"),
                    (5, "General Manager"),
                ],
                default=1,
            ),
        ),
    ]
