# Generated by Django 4.1.7 on 2023-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified_user_phone_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identification",
            field=models.ImageField(null=True, upload_to="id_img/"),
        ),
    ]
