# Generated by Django 4.1.7 on 2023-05-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_identification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False, verbose_name="is phone number verified"
            ),
        ),
    ]
