# Generated by Django 4.1.7 on 2023-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=1, max_length=10, unique=True, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
    ]
