# Generated by Django 4.1.7 on 2023-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="request_id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
