# Generated by Django 4.1.7 on 2023-06-14 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_verified",
        ),
    ]
